server:
  port: 8760
docker:
  image:
    prefix: eurekadockerserver
eureka:
  instance:
    hostname: eurekadockerserver
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/