server:
  port: 8763
spring:
  application:
    name: userserver
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/